// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PVU_PlantScan;

namespace PVU_PlantScan.Migrations
{
    [DbContext(typeof(PlantContext))]
    [Migration("20211029150345_Tables")]
    partial class Tables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("PVU_PlantScan.PlantTableModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<double>("BlockNumber")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("MintTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("PlantId")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TokenId")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Plants");
                });
#pragma warning restore 612, 618
        }
    }
}
